import { useState, useEffect } from "react";
import { analyzeDisasterSignals, analyzeCustomSignal } from "./services/gemini";
import { disasterScenarios } from "./data/mockSignals";
import { demoResponses } from "./data/demoResponses";
import "./index.css";

// ─── Ticker ───────────────────────────────────────────────────────────────────
function Ticker() {
  const items = [
    "● INTELMAP SYSTEM ONLINE",
    "◈ GEMINI AI ENGINE ACTIVE",
    "▸ SATELLITE FEEDS: NOMINAL",
    "▸ IOT SENSOR NETWORK: 1,247 NODES ACTIVE",
    "◈ MULTI-SOURCE SIGNAL FUSION IN PROGRESS",
    "▸ RESPONSE TEAMS ON STANDBY",
    "● 24/7 MONITORING ACTIVE",
    "◈ EXPLAINABLE AI REASONING ENABLED",
  ];
  const repeated = [...items, ...items];
  return (
    <div className="ticker-wrap" style={{ fontSize: "0.58rem", color: "var(--text-muted)", letterSpacing: "0.12em" }}>
      <div className="ticker-inner mono">
        {repeated.map((t, i) => (
          <span key={i} style={{ marginRight: "3rem" }}>{t}</span>
        ))}
      </div>
    </div>
  );
}

// ─── Gemini Tag ───────────────────────────────────────────────────────────────
function GeminiTag({ label = "Explanation Generated by Gemini" }) {
  return (
    <span className="gemini-tag">
      <span className="gemini-tag-dot" />
      {label}
    </span>
  );
}

// ─── Flow Indicator ───────────────────────────────────────────────────────────
function FlowIndicator({ step }) {
  const steps = [
    { num: 1, label: "Input" },
    { num: 2, label: "Gemini Analysis" },
    { num: 3, label: "Explanation" },
    { num: 4, label: "Map" },
  ];

  const getState = (n) => {
    if (step === 0) return n === 1 ? "active" : "idle";
    if (step === 1) return n <= 1 ? "done" : n === 2 ? "active" : "idle";
    if (step === 2) return "done";
    return "idle";
  };

  return (
    <div className="flow-bar">
      {steps.map((s, i) => {
        const state = getState(s.num);
        return (
          <div key={s.num} style={{ display: "flex", alignItems: "center", flex: i < steps.length - 1 ? "1" : "none" }}>
            <div className={`flow-step ${state}`}>
              <div className="flow-step-num">
                {state === "done" ? "✓" : s.num}
              </div>
              <span style={{ whiteSpace: "nowrap" }}>{s.label}</span>
            </div>
            {i < steps.length - 1 && <div className="flow-arrow" />}
          </div>
        );
      })}
    </div>
  );
}

// ─── Demo State Bar ───────────────────────────────────────────────────────────
function DemoBar({ onTrigger }) {
  const [active, setActive] = useState(null);

  const trigger = (state) => {
    setActive(state);
    onTrigger(state);
  };

  const states = [
    {
      id: "success",
      label: "✓ Valid Analysis",
      desc: "Full Gemini response",
      color: "var(--green)",
      bg: "rgba(34,197,94,0.08)",
      border: "rgba(34,197,94,0.35)",
    },
    {
      id: "insufficient",
      label: "⚠ Insufficient Data",
      desc: "Low-confidence signal",
      color: "var(--yellow)",
      bg: "rgba(251,191,36,0.08)",
      border: "rgba(251,191,36,0.35)",
    },
    {
      id: "failed",
      label: "✕ Analysis Failed",
      desc: "API / network error",
      color: "var(--red)",
      bg: "rgba(239,68,68,0.08)",
      border: "rgba(239,68,68,0.35)",
    },
  ];

  return (
    <div style={{
      display: "flex",
      alignItems: "center",
      gap: "0.75rem",
      padding: "0.5rem 1.25rem",
      background: "rgba(255,255,255,0.02)",
      borderBottom: "1px solid var(--border)",
      flexWrap: "wrap",
    }}>
      <div style={{ fontSize: "0.58rem", fontWeight: 700, letterSpacing: "0.14em", color: "var(--text-muted)", textTransform: "uppercase", flexShrink: 0 }}>
        🧪 Test States
      </div>
      <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
        {states.map((s) => (
          <button
            key={s.id}
            onClick={() => trigger(s.id)}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "6px",
              padding: "4px 12px",
              border: `1px solid ${active === s.id ? s.color : s.border}`,
              borderRadius: "6px",
              background: active === s.id ? s.bg : "transparent",
              color: active === s.id ? s.color : "var(--text-muted)",
              fontSize: "0.65rem",
              fontWeight: 700,
              cursor: "pointer",
              letterSpacing: "0.06em",
              transition: "all 0.2s",
              fontFamily: "'Inter', sans-serif",
            }}
          >
            <span style={{ fontWeight: 800 }}>{s.label}</span>
            <span style={{ opacity: 0.6, fontWeight: 400 }}>— {s.desc}</span>
          </button>
        ))}
      </div>
      <div style={{ fontSize: "0.58rem", color: "var(--text-muted)", marginLeft: "auto" }}>
        Uses scenario 1 (Chennai Flood 2026) as base
      </div>
    </div>
  );
}

// ─── Loading State ────────────────────────────────────────────────────────────
function LoadingState({ signals }) {
  const [stepIdx, setStepIdx] = useState(0);
  const loadSteps = [
    "Reading incoming crisis signals…",
    "Cross-referencing locations and sensor data…",
    "Running Gemini classification model…",
    "Generating response plan and explanation…",
  ];

  useEffect(() => {
    setStepIdx(0);
  }, []);

  useEffect(() => {
    if (stepIdx >= loadSteps.length - 1) return;
    const timer = setTimeout(() => setStepIdx((s) => s + 1), 1400);
    return () => clearTimeout(timer);
  }, [stepIdx]);

  return (
    <div className="animate-fadeIn" style={{
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "1.5rem",
      padding: "2rem",
    }}>
      <div className="spinner" />
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: "0.95rem", fontWeight: 700, color: "var(--cyan)", letterSpacing: "0.04em", marginBottom: "0.35rem" }}>
          Analyzing crisis signal using Gemini…
        </div>
        <div style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>
          Processing {signals} signal{signals !== 1 ? "s" : ""} · Please wait
        </div>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.6rem", width: "100%", maxWidth: "320px" }}>
        {loadSteps.map((text, i) => {
          const state = i < stepIdx ? "done" : i === stepIdx ? "active" : "idle";
          return (
            <div key={i} className={`loading-step ${state}`}>
              <div className="loading-step-dot" />
              {text}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Empty State ──────────────────────────────────────────────────────────────
function EmptyState() {
  return (
    <div style={{
      flex: 1, display: "flex", flexDirection: "column",
      alignItems: "center", justifyContent: "center",
      gap: "1rem", padding: "2rem", textAlign: "center",
      color: "var(--text-muted)",
    }}>
      <div style={{ fontSize: "3rem", opacity: 0.18 }}>⬡</div>
      <div>
        <div style={{ fontSize: "0.9rem", fontWeight: 600, color: "var(--text-secondary)", marginBottom: "0.4rem" }}>
          Select an incident feed to begin
        </div>
        <div style={{ fontSize: "0.75rem", lineHeight: 1.7, maxWidth: "260px" }}>
          Choose a disaster scenario from the left, or inject a custom signal.
          Gemini will analyze and explain the crisis.
        </div>
      </div>
      <div style={{ display: "flex", gap: "1.5rem", fontSize: "0.62rem", color: "var(--text-muted)", letterSpacing: "0.1em", marginTop: "0.5rem" }}>
        <span>INPUT →</span>
        <span>GEMINI →</span>
        <span>EXPLANATION →</span>
        <span>MAP</span>
      </div>
    </div>
  );
}

// ─── Action Item ──────────────────────────────────────────────────────────────
function ActionItem({ action, index }) {
  return (
    <div className="action-row animate-fadeInUp" style={{ animationDelay: `${index * 70}ms` }}>
      <div className="action-priority">{action.priority}</div>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: "0.8rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "2px" }}>
          {action.action}
          {action.time_sensitive && (
            <span style={{ marginLeft: "8px", fontSize: "0.58rem", color: "var(--red)", border: "1px solid var(--red)", borderRadius: "3px", padding: "1px 5px", verticalAlign: "middle" }}>
              URGENT
            </span>
          )}
        </div>
        <div style={{ fontSize: "0.67rem", color: "var(--text-muted)" }}>{action.sector}</div>
      </div>
    </div>
  );
}

// ─── Signal Row ───────────────────────────────────────────────────────────────
function SignalRow({ signal, index }) {
  const srcClass = `src-${signal.source.replace(/\s/g, "_")}`;
  return (
    <div className="signal-row animate-fadeInUp" style={{ animationDelay: `${index * 50}ms` }}>
      <span className="mono" style={{ color: "var(--cyan)", opacity: 0.7 }}>{signal.timestamp}</span>
      <span className={`mono ${srcClass}`} style={{ fontWeight: 600 }}>{signal.source.replace(/_/g, " ")}</span>
      <span style={{ color: "var(--text-primary)" }}>{signal.value}</span>
      <span style={{ color: "var(--text-muted)", textAlign: "right", whiteSpace: "nowrap" }}>{signal.location}</span>
    </div>
  );
}

// ─── Map Panel ────────────────────────────────────────────────────────────────
function MapPanel({ scenario }) {
  if (!scenario) {
    return (
      <div className="map-placeholder">
        <div style={{ fontSize: "2.5rem", opacity: 0.15 }}>🗺</div>
        <div style={{ fontWeight: 600, color: "var(--text-secondary)", fontSize: "0.82rem" }}>Map will appear here</div>
        <div style={{ fontSize: "0.7rem", lineHeight: 1.7, maxWidth: "220px" }}>
          Once an incident is selected, the affected zone will be pinned on the map.
        </div>
      </div>
    );
  }

  const { lat, lng, name } = scenario;
  const mapSrc = `https://maps.google.com/maps?q=${lat},${lng}&z=11&output=embed`;

  return (
    <>
      <div style={{ padding: "0.75rem 1rem", borderBottom: "1px solid var(--border)" }}>
        <div className="label">Location Context — Map</div>
        <div style={{ fontSize: "0.72rem", color: "var(--text-secondary)", marginTop: "4px" }}>
          📍 Incident zone: <span style={{ color: "var(--text-primary)", fontWeight: 600 }}>{name}</span>
        </div>
        <div className="mono" style={{ fontSize: "0.6rem", color: "var(--text-muted)", marginTop: "2px" }}>
          {lat.toFixed(4)}°N, {Math.abs(lng).toFixed(4)}°E
        </div>
      </div>
      <iframe
        key={scenario.id}
        className="map-iframe animate-fadeIn"
        src={mapSrc}
        title={`Map — ${name}`}
        loading="lazy"
        allowFullScreen
        referrerPolicy="no-referrer-when-downgrade"
      />
    </>
  );
}

// ─── Gemini Result Panel ──────────────────────────────────────────────────────
function GeminiResultPanel({ analysis, scenario }) {
  const threatColors = {
    CRITICAL: "var(--red)",
    HIGH: "var(--orange)",
    MEDIUM: "var(--yellow)",
    LOW: "var(--green)",
  };
  const threatColor = threatColors[analysis.threat_level] ?? "var(--cyan)";

  const scenarioColorMap = { 1: "var(--blue)", 2: "var(--orange)", 3: "var(--red)", 4: "var(--purple)" };
  const chipColor = scenario ? (scenarioColorMap[scenario.id] ?? "var(--cyan)") : "var(--cyan)";

  return (
    <>
      {/* Hero: Emergency Type + Severity */}
      <div className="card animate-fadeInUp" style={{
        border: `1px solid ${threatColor}30`,
        background: `linear-gradient(135deg, ${threatColor}07 0%, transparent 60%)`,
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", flexWrap: "wrap", marginBottom: "0.75rem" }}>
          {scenario && (
            <span style={{
              display: "inline-flex", alignItems: "center", gap: "6px",
              padding: "4px 14px 4px 10px", borderRadius: "6px",
              fontSize: "0.8rem", fontWeight: 700, letterSpacing: "0.05em", textTransform: "uppercase",
              border: `1px solid ${chipColor}`, color: chipColor, background: `${chipColor}12`,
            }}>
              {scenario.emoji} {scenario.name}
            </span>
          )}
          <span className={`badge badge-${analysis.threat_level}`}>{analysis.threat_level}</span>
          <GeminiTag label="AI Classification" />
        </div>
        <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)", lineHeight: 1.6 }}>
          {analysis.primary_threat}
        </div>
      </div>

      {/* Gemini Explanation */}
      <div className="card-gemini animate-fadeInUp" style={{ animationDelay: "80ms" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.65rem", marginBottom: "0.85rem" }}>
          <div style={{ fontSize: "0.62rem", fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--cyan)" }}>
            ⬡ GEMINI AI REASONING
          </div>
          <GeminiTag label="Explanation Generated by Gemini" />
        </div>
        <div className="reasoning-block">{analysis.reasoning}</div>

        {analysis.next_6_hours_prediction && (
          <div style={{ marginTop: "1rem", padding: "0.75rem 1rem", background: "rgba(239,68,68,0.05)", border: "1px solid rgba(239,68,68,0.2)", borderRadius: "8px" }}>
            <div className="label" style={{ color: "var(--red)", marginBottom: "6px" }}>
              ⚠ GEMINI PREDICTION — If No Action Taken
            </div>
            <p style={{ fontSize: "0.78rem", color: "var(--text-secondary)", lineHeight: 1.65 }}>
              {analysis.next_6_hours_prediction}
            </p>
          </div>
        )}
      </div>

      {/* Actions + Resources */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem", animationDelay: "160ms" }} className="animate-fadeInUp">
        <div className="card">
          <div className="label" style={{ marginBottom: "0.75rem" }}>Immediate Action Orders</div>
          {analysis.immediate_actions?.map((a, i) => <ActionItem key={i} action={a} index={i} />)}
        </div>
        <div className="card">
          <div className="label" style={{ marginBottom: "0.75rem" }}>Resource Allocation</div>
          <div className="stat-grid">
            {[
              { val: analysis.resource_allocation?.rescue_units, label: "Rescue Units", color: "var(--cyan)" },
              { val: analysis.resource_allocation?.medical_teams, label: "Medical Teams", color: "var(--green)" },
              { val: analysis.resource_allocation?.supply_drops, label: "Supply Drops", color: "var(--yellow)" },
              { val: analysis.resource_allocation?.evacuation_buses, label: "Evac. Buses", color: "var(--orange)" },
            ].map((item) => (
              <div key={item.label} className="stat-cell">
                <div className="stat-value" style={{ color: item.color }}>{item.val ?? "—"}</div>
                <div className="stat-label">{item.label}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Impact Row */}
      <div className="card animate-fadeInUp" style={{ animationDelay: "220ms" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "1rem" }}>
          <div>
            <div className="label" style={{ marginBottom: "6px" }}>Est. Affected Population</div>
            <div style={{ fontSize: "1rem", fontWeight: 700, color: "var(--orange)" }}>
              {analysis.estimated_affected_population ?? "Calculating…"}
            </div>
          </div>
          <div>
            <div className="label" style={{ marginBottom: "6px" }}>Affected Zones</div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "4px" }}>
              {analysis.affected_zones?.map((z, i) => (
                <span key={i} className="badge" style={{ color: "var(--text-secondary)", borderColor: "var(--border-active)" }}>{z}</span>
              ))}
            </div>
          </div>
          <div>
            <div className="label" style={{ marginBottom: "6px" }}>Signal Credibility</div>
            <div style={{ display: "flex", flexDirection: "column", gap: "4px", fontSize: "0.72rem" }}>
              <span style={{ color: "var(--green)" }}>● {analysis.signal_credibility?.high ?? 0} High</span>
              <span style={{ color: "var(--yellow)" }}>● {analysis.signal_credibility?.medium ?? 0} Medium</span>
              <span style={{ color: "var(--red)" }}>● {analysis.signal_credibility?.low ?? 0} Low</span>
            </div>
          </div>
        </div>
      </div>

      {/* Signal Feed */}
      {scenario && (
        <div className="card animate-fadeInUp" style={{ animationDelay: "300ms" }}>
          <div className="label" style={{ marginBottom: "0.75rem" }}>
            Incoming Signal Feed — {scenario.name} ({scenario.signals.length} signals)
          </div>
          <div style={{ maxHeight: "180px", overflowY: "auto" }}>
            {scenario.signals.map((s, i) => <SignalRow key={i} signal={s} index={i} />)}
          </div>
        </div>
      )}
    </>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [selectedScenario, setSelectedScenario] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [insufficientData, setInsufficientData] = useState(false);
  const [customSignal, setCustomSignal] = useState("");
  const [customLoading, setCustomLoading] = useState(false);
  const [inputError, setInputError] = useState(null);
  const [time, setTime] = useState(new Date().toLocaleTimeString());

  useEffect(() => {
    const t = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000);
    return () => clearTimeout(t);
  }, []);

  const flowStep = loading || customLoading ? 1 : analysis || error || insufficientData ? 2 : 0;

  // ── Demo state trigger ──
  const handleDemoState = (state) => {
    const baseScenario = disasterScenarios[0]; // Chennai Flood 2026
    setSelectedScenario(baseScenario);
    setAnalysis(null);
    setError(null);
    setInsufficientData(false);
    setInputError(null);

    if (state === "success") {
      // Show real mock Gemini response
      setAnalysis(demoResponses[1]);
    } else if (state === "insufficient") {
      // Simulate ambiguous data — no threat_level returned
      setInsufficientData(true);
    } else if (state === "failed") {
      // Simulate API/network failure
      setError("Gemini service unavailable — check your API key in the .env file.");
    }
  };

  // ── Live Gemini analyze ──
  const handleAnalyze = async (scenario) => {
    setSelectedScenario(scenario);
    setLoading(true);
    setAnalysis(null);
    setError(null);
    setInsufficientData(false);
    setInputError(null);
    try {
      const result = await analyzeDisasterSignals(scenario.signals, scenario.name);
      if (!result?.threat_level) {
        setInsufficientData(true);
      } else {
        setAnalysis(result);
      }
    } catch (err) {
      console.error("Gemini error:", err);
      setError("Gemini service unavailable — check your API key in the .env file.");
    } finally {
      setLoading(false);
    }
  };

  // ── Custom Signal ──
  const handleCustomSignal = async () => {
    if (!customSignal.trim() && !selectedScenario) {
      setInputError("Please describe a crisis signal or select an incident feed first.");
      return;
    }
    if (!customSignal.trim()) {
      setInputError("Please enter a signal description before analyzing.");
      return;
    }
    setInputError(null);
    setCustomLoading(true);
    setError(null);
    setInsufficientData(false);
    try {
      const result = await analyzeCustomSignal(customSignal, selectedScenario?.signals ?? []);
      if (!result?.threat_level) {
        setInsufficientData(true);
      } else {
        setAnalysis(result);
        setCustomSignal("");
      }
    } catch (err) {
      console.error("Custom signal error:", err);
      setError("Gemini service unavailable — please try again.");
    } finally {
      setCustomLoading(false);
    }
  };

  const isLoading = loading || customLoading;

  return (
    <div className="grid-bg" style={{ minHeight: "100vh", background: "var(--bg-primary)", display: "flex", flexDirection: "column" }}>

      {/* ── Header ── */}
      <header className="app-header">
        <div style={{ display: "flex", alignItems: "center", gap: "0.9rem" }}>
          <div style={{ width: "38px", height: "38px", border: "2px solid var(--cyan)", borderRadius: "9px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.15rem", boxShadow: "0 0 14px rgba(34,211,238,0.35)", flexShrink: 0 }}>⬡</div>
          <div>
            <div style={{ fontSize: "1.25rem", fontWeight: 900, color: "var(--cyan)", letterSpacing: "0.1em", lineHeight: 1.1 }}>INTELMAP</div>
            <div style={{ fontSize: "0.58rem", color: "var(--text-muted)", letterSpacing: "0.08em" }}>
              Explainable, Location-Aware Crisis Intelligence
            </div>
          </div>
        </div>
        <div style={{ flex: 1, margin: "0 1.5rem", overflow: "hidden" }}><Ticker /></div>
        <div style={{ display: "flex", alignItems: "center", gap: "1.25rem", flexShrink: 0 }}>
          <div style={{ textAlign: "right" }}>
            <div className="mono" style={{ fontSize: "0.88rem", color: "var(--text-primary)", fontWeight: 600 }}>{time}</div>
            <div style={{ fontSize: "0.6rem", color: "var(--text-muted)", letterSpacing: "0.08em" }}>UTC+5:30</div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: "6px", padding: "4px 10px", background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.3)", borderRadius: "20px" }}>
            <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "var(--green)", display: "inline-block" }} className="animate-pulse-slow" />
            <span style={{ fontSize: "0.6rem", fontWeight: 700, color: "var(--green)", letterSpacing: "0.1em" }}>GEMINI ONLINE</span>
          </div>
        </div>
      </header>

      {/* ── Demo State Bar ── */}
      <DemoBar onTrigger={handleDemoState} />

      {/* ── Body ── */}
      <div className="app-body" style={{ flex: 1 }}>

        {/* LEFT PANEL */}
        <aside className="panel-left">
          <div style={{ padding: "1rem", borderBottom: "1px solid var(--border)" }}>
            <div className="label" style={{ marginBottom: "0.5rem" }}>Select Incident Feed</div>
            <div style={{ fontSize: "0.68rem", color: "var(--text-muted)", lineHeight: 1.6 }}>
              Choose a disaster scenario to begin Gemini analysis.
            </div>
          </div>

          <div style={{ padding: "0.75rem", display: "flex", flexDirection: "column", gap: "0.5rem", flex: 1 }}>
            {disasterScenarios.map((s) => {
              const active = selectedScenario?.id === s.id;
              return (
                <button key={s.id} onClick={() => handleAnalyze(s)} disabled={isLoading}
                  className={`scenario-btn ${active ? "active" : ""}`}
                  style={{ border: `1px solid ${active ? s.color : "var(--border)"}` }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                    <div style={{ fontSize: "1.25rem", marginBottom: "4px" }}>{s.emoji}</div>
                    {active && (
                      <span style={{ fontSize: "0.55rem", fontWeight: 700, letterSpacing: "0.1em", color: s.color, background: `${s.color}18`, border: `1px solid ${s.color}50`, borderRadius: "4px", padding: "1px 6px" }}>ACTIVE</span>
                    )}
                  </div>
                  <div style={{ fontWeight: 700, fontSize: "0.8rem", color: active ? s.color : "var(--text-primary)" }}>{s.name}</div>
                  <div style={{ fontSize: "0.67rem", color: "var(--text-muted)", marginTop: "2px" }}>{s.location}</div>
                  <div style={{ fontSize: "0.62rem", color: "var(--text-muted)", marginTop: "4px" }}>
                    {s.signals.length} signals · {s.lat.toFixed(2)}°N
                  </div>
                </button>
              );
            })}
          </div>

          {/* Custom Signal */}
          <div style={{ padding: "1rem", borderTop: "1px solid var(--border)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.6rem" }}>
              <div className="label">Inject Custom Signal</div>
              <GeminiTag label="via Gemini" />
            </div>
            <textarea
              className="signal-textarea"
              value={customSignal}
              onChange={(e) => { setCustomSignal(e.target.value); setInputError(null); }}
              placeholder={`e.g. "Dam breach reported near Sector 9 — 800 families at risk"`}
              rows={3}
              onKeyDown={(e) => { if (e.key === "Enter" && e.ctrlKey) handleCustomSignal(); }}
            />
            {inputError && (
              <div style={{ fontSize: "0.68rem", color: "var(--red)", marginTop: "0.4rem", lineHeight: 1.5 }}>⚠ {inputError}</div>
            )}
            <button className="btn-analyze" onClick={handleCustomSignal}
              disabled={customLoading || (!customSignal.trim() && !selectedScenario)}
              style={{ marginTop: "0.6rem" }}>
              {customLoading
                ? <><div className="spinner" style={{ width: "14px", height: "14px", borderWidth: "2px" }} /> Analyzing…</>
                : "⬡ Analyze with Gemini"}
            </button>
            <div style={{ fontSize: "0.58rem", color: "var(--text-muted)", textAlign: "center", marginTop: "0.4rem" }}>
              Ctrl + Enter to submit
            </div>
          </div>
        </aside>

        {/* CENTER PANEL */}
        <div className="panel-center">
          <FlowIndicator step={flowStep} />
          <div className="panel-center-scroll">

            {/* ── State: Analysis Failed ── */}
            {error && !isLoading && (
              <div className="error-banner animate-fadeIn">
                <span style={{ fontSize: "1.3rem", flexShrink: 0 }}>✕</span>
                <div>
                  <div style={{ fontWeight: 700, marginBottom: "4px", fontSize: "0.85rem" }}>Analysis Failed</div>
                  <div style={{ lineHeight: 1.65 }}>{error}</div>
                  <div style={{ marginTop: "0.5rem", fontSize: "0.7rem", color: "rgba(252,165,165,0.7)" }}>
                    Check your <code style={{ background: "rgba(239,68,68,0.1)", padding: "1px 4px", borderRadius: "3px" }}>.env</code> file and ensure <code style={{ background: "rgba(239,68,68,0.1)", padding: "1px 4px", borderRadius: "3px" }}>VITE_GEMINI_API_KEY</code> is set correctly.
                  </div>
                </div>
              </div>
            )}

            {/* ── State: Insufficient Data ── */}
            {insufficientData && !isLoading && (
              <div className="animate-fadeIn" style={{
                display: "flex", alignItems: "flex-start", gap: "0.75rem",
                padding: "1rem", background: "rgba(251,191,36,0.06)",
                border: "1px solid rgba(251,191,36,0.3)", borderRadius: "10px",
                color: "#fde68a", fontSize: "0.78rem", lineHeight: 1.6,
              }}>
                <span style={{ fontSize: "1.3rem", flexShrink: 0 }}>⚠</span>
                <div>
                  <div style={{ fontWeight: 700, marginBottom: "4px", fontSize: "0.85rem" }}>Insufficient Data to Classify</div>
                  <div>
                    The signals provided are too weak, incomplete, or ambiguous for Gemini to make a confident classification.
                  </div>
                  <div style={{ marginTop: "0.5rem", fontSize: "0.7rem", color: "rgba(253,230,138,0.7)" }}>
                    Try adding more specific signals — include location, severity level, or source type for better accuracy.
                  </div>
                </div>
              </div>
            )}

            {/* ── State: Loading ── */}
            {isLoading && <LoadingState signals={selectedScenario?.signals.length ?? 1} />}

            {/* ── State: Empty ── */}
            {!selectedScenario && !isLoading && !error && !insufficientData && <EmptyState />}

            {/* ── State: Full Analysis (Success) ── */}
            {analysis?.threat_level && !isLoading && (
              <GeminiResultPanel analysis={analysis} scenario={selectedScenario} />
            )}

          </div>
        </div>

        {/* RIGHT PANEL — Map */}
        <div className="panel-right">
          <div style={{ padding: "0.75rem 1rem", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <div className="label" style={{ flex: 1 }}>Location Map</div>
            <span style={{ fontSize: "0.6rem", color: "var(--text-muted)" }}>Maps = context, not decoration</span>
          </div>
          <MapPanel scenario={selectedScenario} />
        </div>

      </div>
    </div>
  );
}
